[package]
name = "redis_json"
version = "99.99.99"
authors = ["Guy Korland <guy.korland@redis.com>", "Meir Shpilraien <meir@redis.com>", "Omer Shadmi <omer.shadmi@redis.com>"]
edition.workspace = true
description = "JSON data type for Redis"
repository.workspace = true
readme = "README.md" 
license.workspace = true
keywords = ["redis", "json", "plugin"]
categories = ["database-implementations"]
homepage = "https://redis.io/docs/stack/json/"

[lib]
crate-type = ["cdylib", "rlib"]
name = "rejson"

[dev-dependencies]
env_logger = "0.10.0"

[dependencies]
bitflags = "1.3"
bson = "0.14"
ijson.workspace = true
serde_json.workspace = true
serde.workspace = true
libc = "0.2"
redis-module = { version="1.0", features = ["experimental-api"]}
itertools = "0.10"
json_path = {path="../json_path"}

[features]
# Workaround to allow cfg(feature = "test") in redismodue-rs dependencies:
# https://github.com/RedisLabsModules/redismodule-rs/pull/68
# This requires running the tests with `--features test`
test = ["redis-module/test"]
as-library = []

[profile.release]
debug = 1
