[workspace]

members = [
    "json_path",
    "redis_json"
]

[workspace.dependencies]
ijson = "0.1.3"
serde_json = { version="1.0", features = ["unbounded_depth"]}
serde = "1.0"

[workspace.package]
edition = "2021"
repository = "https://github.com/RedisJSON/RedisJSON"
license = "Redis Source Available License 2.0 (RSALv2) or the Server Side Public License v1 (SSPLv1)"
